apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  containers:
  - image: nginx:alpine
    name: test
    resources: {}
    volumeMounts:
    - name: myvol
      mountPath: /test
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: myvol
    hostPath:
      path: /
status: {}
